import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Load the Poppins font and expose it via a CSS variable
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Knight Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
